# config/routes.yaml

index:
    path:    /
    controller: App\Controller\Controller::index



planningRecurrent_admin:
    path:     /admin/planningRecurrent
    controller: App\Controller\PlanningRecurrentController::indexActionAdmin
    methods:  [GET]

planningRecurrent:
    path:     /planningRecurrent
    controller: App\Controller\PlanningRecurrentController::indexAction
    methods:  [GET]

planningRecurrent_create:
    path:     /admin/planningRecurrent_create
    controller: App\Controller\PlanningRecurrentController::createAction
    methods:  [POST]

planningRecurrent_update:
    path:     /admin/planningRecurrent_update
    controller: App\Controller\PlanningRecurrentController::updateAction
    methods:  [POST]

planningRecurrent_delete:
    path:     /admin/planningRecurrent_delete
    controller: App\Controller\PlanningRecurrentController::deleteAction
    methods:  [DELETE]

planningOccasionnel_admin:
    path:     /admin/planningOccasionnel
    controller: App\Controller\PlanningOccasionnelController::indexActionAdmin
    methods:  [GET]

planningOccasionnel:
    path:     /planningOccasionnel
    controller: App\Controller\PlanningOccasionnelController::indexAction
    methods:  [GET]

planningOccasionnel_create:
    path:     /admin/planningOccasionnel_create
    controller: App\Controller\PlanningOccasionnelController::createAction
    methods:  [POST]

planningOccasionnel_update:
    path:     /admin/planningOccasionnel_update
    controller: App\Controller\PlanningOccasionnelController::updateAction
    methods:  [POST]

planningOccasionnel_delete:
    path:     /admin/planningOccasionnel_delete
    controller: App\Controller\PlanningOccasionnelController::deleteAction
    methods:  [DELETE]