# config/routes.yaml

home:
    path:    /home
    controller: App\Controller\HomeController::showHome

blog:
    path: /blog/{id}
    controller: App\Controller\HomeController::showOnePost

dashboard:
    path:   /bo
    controller: App\Controller\HomeController::showDashBoard

logout:
    path:   /logout
    controller: App\Controller\HomeController::logout

login:
    path:   /login
    controller: App\Controller\HomeController::login

update:
    path: /bo/update/{id}
    controller: App\Controller\HomeController::form

createPost:
    path: /bo/createpost
    controller: App\Controller\HomeController::form

delete:
    path: /bo/delete/{id}
    controller: App\Controller\HomeController::delete

post:
    path: /post
    controller: App\Controller\HomeController::showAllPost